### PR TITLE
Auto-format backend code with black

### PR DESCRIPTION
**Pull request by Iinh**
We currently have `npm run format` to auto-format front-end code with Prettier, and lint check with ESLint. This PR standardizes code styling with `black` code formatter and `flake8` lint check.

- Reformat the current `.py` files with `black`
- To make formatting more convenient, add `make format` and `make lint` commands
- Add back-end linting check to CI check

### CODE REVIEW

**Comment by Iinh** [comment]
Tests should pass once #1950 is merged.

**Comment by edugfilho** [comment]
wrt the ci test failure, is it due to [package.json v2](https://github.com/mozilla/glam/pull/1950)? If so, is the plan to bring that fix to this branch, from main, before merging?

**Comment by Iinh** [comment]
> wrt the ci test failure, is it due to [package.json v2](https://github.com/mozilla/glam/pull/1950)? If so, is the plan to bring that fix to this branch, from main, before merging?

Strange, after retriggering the tests by force-pushing they all passed? Looks like some intermittent CI issue? Anyway, I'm going to close #1950 for now. Will revisit that PR again if we run into the same issue in the future.

**Review by edugfilho — APPROVED** [review]
excellent work. Thanks a lot for doing this!

**Pull request merged**
