### PR TITLE
Lint

### PR DESCRIPTION
**Pull request by Iinh**
Trying to fix the currently failing back-end test, starting with linting first.

### CODE REVIEW

**Comment by Iinh** [comment]
@edugfilho from the CircleCI log, the currently failing test `TestRandomProbesApi.test_response` looks related to #2742, which was when CI started failing it seems. Could you help check?

**Comment by edugfilho** [comment]
Yes, I'll fix the tests!

**Review by edugfilho — APPROVED** [review]
All tests are successful. r+

**Comment by edugfilho** [comment]
Thanks for fixing that annoying lint issue @Iinh!

**Pull request merged**
